version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-cubes"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eyip8r8q9eqn"
s3_prefix = "cloud-cubes"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Database=\"minecraft-servers\""
