AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-cubes

  Sample SAM Template for cloud-cubes

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  SchedulerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scheduler/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonEC2FullAccess
      Environment:
        Variables:
          DATABASE_NAME: minecraft-servers

Outputs:
  SchedulerFunction:
    Description: "Scheduler Function ARN"
    Value: !GetAtt SchedulerFunction.Arn
  SchedulerFunctionIamRole:
    Description: "Implicit IAM Role created for Scheduler function"
    Value: !GetAtt SchedulerFunctionRole.Arn
